# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: speed_profile_debug.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='speed_profile_debug.proto',
  package='planning.debug.speed',
  syntax='proto2',
  serialized_pb=_b('\n\x19speed_profile_debug.proto\x12\x14planning.debug.speed\"\x99\x02\n\x11SpeedProfileDebug\x12+\n\x04tree\x18\x01 \x03(\x0b\x32\x1d.planning.debug.speed.stState\x12.\n\x07st_path\x18\x02 \x03(\x0b\x32\x1d.planning.debug.speed.stState\x12\x36\n\x0eprediction_veh\x18\x03 \x01(\x0b\x32\x1e.planning.debug.speed.xyStates\x12\x36\n\x0eprediction_obs\x18\x04 \x03(\x0b\x32\x1e.planning.debug.speed.xyStates\x12\x37\n\x0c\x64istance_map\x18\x05 \x01(\x0b\x32!.planning.debug.speed.DistanceMap\"O\n\x07stState\x12\t\n\x01t\x18\x01 \x01(\x01\x12\t\n\x01s\x18\x02 \x01(\x01\x12\t\n\x01v\x18\x03 \x01(\x01\x12\r\n\x05index\x18\x04 \x01(\x05\x12\x14\n\x0cparent_index\x18\x05 \x01(\x05\"9\n\x08xyStates\x12-\n\x06states\x18\x01 \x03(\x0b\x32\x1d.planning.debug.speed.xyState\".\n\x07xyState\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\r\n\x05theta\x18\x03 \x01(\x01\"<\n\x0b\x44istanceMap\x12-\n\x06points\x18\x01 \x03(\x0b\x32\x1d.planning.debug.speed.stState')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SPEEDPROFILEDEBUG = _descriptor.Descriptor(
  name='SpeedProfileDebug',
  full_name='planning.debug.speed.SpeedProfileDebug',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tree', full_name='planning.debug.speed.SpeedProfileDebug.tree', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='st_path', full_name='planning.debug.speed.SpeedProfileDebug.st_path', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='prediction_veh', full_name='planning.debug.speed.SpeedProfileDebug.prediction_veh', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='prediction_obs', full_name='planning.debug.speed.SpeedProfileDebug.prediction_obs', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='distance_map', full_name='planning.debug.speed.SpeedProfileDebug.distance_map', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=333,
)


_STSTATE = _descriptor.Descriptor(
  name='stState',
  full_name='planning.debug.speed.stState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='t', full_name='planning.debug.speed.stState.t', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='s', full_name='planning.debug.speed.stState.s', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='v', full_name='planning.debug.speed.stState.v', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='index', full_name='planning.debug.speed.stState.index', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='parent_index', full_name='planning.debug.speed.stState.parent_index', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=335,
  serialized_end=414,
)


_XYSTATES = _descriptor.Descriptor(
  name='xyStates',
  full_name='planning.debug.speed.xyStates',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='states', full_name='planning.debug.speed.xyStates.states', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=416,
  serialized_end=473,
)


_XYSTATE = _descriptor.Descriptor(
  name='xyState',
  full_name='planning.debug.speed.xyState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='planning.debug.speed.xyState.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='planning.debug.speed.xyState.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='theta', full_name='planning.debug.speed.xyState.theta', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=475,
  serialized_end=521,
)


_DISTANCEMAP = _descriptor.Descriptor(
  name='DistanceMap',
  full_name='planning.debug.speed.DistanceMap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='points', full_name='planning.debug.speed.DistanceMap.points', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=523,
  serialized_end=583,
)

_SPEEDPROFILEDEBUG.fields_by_name['tree'].message_type = _STSTATE
_SPEEDPROFILEDEBUG.fields_by_name['st_path'].message_type = _STSTATE
_SPEEDPROFILEDEBUG.fields_by_name['prediction_veh'].message_type = _XYSTATES
_SPEEDPROFILEDEBUG.fields_by_name['prediction_obs'].message_type = _XYSTATES
_SPEEDPROFILEDEBUG.fields_by_name['distance_map'].message_type = _DISTANCEMAP
_XYSTATES.fields_by_name['states'].message_type = _XYSTATE
_DISTANCEMAP.fields_by_name['points'].message_type = _STSTATE
DESCRIPTOR.message_types_by_name['SpeedProfileDebug'] = _SPEEDPROFILEDEBUG
DESCRIPTOR.message_types_by_name['stState'] = _STSTATE
DESCRIPTOR.message_types_by_name['xyStates'] = _XYSTATES
DESCRIPTOR.message_types_by_name['xyState'] = _XYSTATE
DESCRIPTOR.message_types_by_name['DistanceMap'] = _DISTANCEMAP

SpeedProfileDebug = _reflection.GeneratedProtocolMessageType('SpeedProfileDebug', (_message.Message,), dict(
  DESCRIPTOR = _SPEEDPROFILEDEBUG,
  __module__ = 'speed_profile_debug_pb2'
  # @@protoc_insertion_point(class_scope:planning.debug.speed.SpeedProfileDebug)
  ))
_sym_db.RegisterMessage(SpeedProfileDebug)

stState = _reflection.GeneratedProtocolMessageType('stState', (_message.Message,), dict(
  DESCRIPTOR = _STSTATE,
  __module__ = 'speed_profile_debug_pb2'
  # @@protoc_insertion_point(class_scope:planning.debug.speed.stState)
  ))
_sym_db.RegisterMessage(stState)

xyStates = _reflection.GeneratedProtocolMessageType('xyStates', (_message.Message,), dict(
  DESCRIPTOR = _XYSTATES,
  __module__ = 'speed_profile_debug_pb2'
  # @@protoc_insertion_point(class_scope:planning.debug.speed.xyStates)
  ))
_sym_db.RegisterMessage(xyStates)

xyState = _reflection.GeneratedProtocolMessageType('xyState', (_message.Message,), dict(
  DESCRIPTOR = _XYSTATE,
  __module__ = 'speed_profile_debug_pb2'
  # @@protoc_insertion_point(class_scope:planning.debug.speed.xyState)
  ))
_sym_db.RegisterMessage(xyState)

DistanceMap = _reflection.GeneratedProtocolMessageType('DistanceMap', (_message.Message,), dict(
  DESCRIPTOR = _DISTANCEMAP,
  __module__ = 'speed_profile_debug_pb2'
  # @@protoc_insertion_point(class_scope:planning.debug.speed.DistanceMap)
  ))
_sym_db.RegisterMessage(DistanceMap)


# @@protoc_insertion_point(module_scope)
